[theme]
base = "dark"
primaryColor = "#E62429"
backgroundColor = "#0A0A14"
secondaryBackgroundColor = "#141428"
textColor = "#F6F6FB"
font = "sans serif"

[server]
# Streamlit Cloud မှာ headless run
headless = true
